version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          build: "npm run build"
          post-steps:
            - run:
                name: Check Types
                command: yarn types
            # - run:
            #     name: Unit Tests
            #     command: yarn test:unit
      - cypress/run:
          name: "API Tests"
          requires:
            - cypress/install
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          spec: cypress/tests/api/*
          parallel: true
          group: API
      - cypress/run:
          name: "UI Tests - Chrome"
          requires:
            - cypress/install
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          parallelism: 2
          spec: cypress/tests/ui/*
          group: "UI - Chrome"
      - cypress/run:
        name: "UI Tests - Firefox"
        requires:
          - cypress/install
        executor: cypress/browsers-chrome78-ff70
        browser: firefox
        yarn: true
        start: yarn test:ci
        wait-on: "http://localhost:3000"
        record: true
        parallel: true
        parallelism: 2
        spec: cypress/tests/ui/*
        group: "UI - Firefox"
