version: 2.1
orbs:
  cypress: cypress-io/cypress@1.22.0
  codecov: codecov/codecov@1.0.5

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
workflows:
  build:
    jobs:
      # Setup
      #  1. Install Cypress
      #  2. Build application
      #  3. Validate types
      #  4. Run server unit-tests
      - cypress/install:
          name: "Setup"
          yarn: true
          executor: cypress/browsers-chrome78-ff70
          build: "npm run build"
          post-steps:
            - run:
                name: Check Types
                command: yarn types
            - run:
                name: Run Unit Tests
                command: yarn test:unit

      # Run API tests against backend server
      - cypress/run:
          name: "API Tests"
          browser: chrome
          spec: cypress/tests/api/*
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn test:ci
          record: true
          parallel: true
          parallelism: 4
          group: API
          requires:
            - Setup
          post-steps:
            - codecov/upload:
                file: coverage/lcov.info
                flag: cypress

      # Run E2E tests in Chrome
      - cypress/run:
          name: "UI Tests - Chrome"
          browser: chrome
          spec: cypress/tests/ui/*
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn test:ci
          record: true
          parallel: true
          parallelism: 4
          group: "UI - Chrome"
          requires:
            - Setup
          post-steps:
            - codecov/upload:
                file: coverage/lcov.info
                flag: cypress

      # Run E2E tests in Chrome with mobile device viewport
      - cypress/run:
          name: "UI Tests - Chrome - Mobile"
          browser: chrome
          spec: cypress/tests/ui/*
          config: "viewportWidth=375,viewportHeight=667"
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn test:ci
          record: true
          parallel: true
          parallelism: 4
          group: "UI - Chrome - Mobile"
          requires:
            - Setup
          post-steps:
            - codecov/upload:
                file: coverage/lcov.info
                flag: cypress

      # Run E2E tests in Firefox
      - cypress/run:
          name: "UI Tests - Firefox"
          browser: firefox
          spec: cypress/tests/ui/*
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn test:ci
          record: true
          parallel: true
          parallelism: 4
          group: "UI - Firefox"
          requires:
            - Setup
          post-steps:
            - codecov/upload:
                file: coverage/lcov.info
                flag: cypress

      # Run E2E tests in Firefox with mobile device viewport
      - cypress/run:
          name: "UI Tests - Firefox - Mobile"
          browser: firefox
          spec: cypress/tests/ui/*
          config: "viewportWidth=375,viewportHeight=667"
          wait-on: "http://localhost:3000"
          executor: cypress/browsers-chrome78-ff70
          yarn: true
          start: yarn test:ci
          record: true
          parallel: true
          parallelism: 4
          group: "UI - Firefox - Mobile"
          requires:
            - Setup
          post-steps:
            - codecov/upload:
                file: coverage/lcov.info
                flag: cypress
      # - report-full-coverage:
      #     name: "Report Code Coverage"
      #     requires:
      #       - "API Tests"
      #       - "UI Tests - Chrome"
      #       - "UI Tests - Chrome - Mobile"
      #       - "UI Tests - Firefox"
      #       - "UI Tests - Firefox - Mobile"
